# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(281, 270)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 20, 161, 20))
        self.label.setStyleSheet("font: 12pt \"Book Antiqua\";")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 110, 231, 49))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 60, 231, 49))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_log = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_log.setAutoFillBackground(False)
        self.lineEdit_log.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.lineEdit_log.setText("")
        self.lineEdit_log.setObjectName("lineEdit_log")
        self.verticalLayout.addWidget(self.lineEdit_log)
        self.lineEdit_pas = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pas.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.lineEdit_pas.setObjectName("lineEdit_pas")
        self.verticalLayout_2.addWidget(self.lineEdit_pas)
        self.pushButton_reg = QtWidgets.QPushButton(Form)
        self.pushButton_reg.setGeometry(QtCore.QRect(60, 240, 161, 21))
        self.pushButton_reg.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"font: 9pt \"Book Antiqua\";")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.pushButton_ex = QtWidgets.QPushButton(Form)
        self.pushButton_ex.setGeometry(QtCore.QRect(180, 165, 75, 23))
        self.pushButton_ex.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"font: 9pt \"Book Antiqua\";")
        self.pushButton_ex.setObjectName("pushButton_ex")
        self.waring = QtWidgets.QLabel(Form)
        self.waring.setGeometry(QtCore.QRect(20, 190, 231, 31))
        self.waring.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.waring.setObjectName("waring")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вход"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#393939;\">Добро пожаловать!</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#0055ff;\">Введите пароль:</span></p></body></html>"))
        self.pushButton_reg.setText(_translate("Form", "Зарегистрироваться"))
        self.pushButton_ex.setText(_translate("Form", "Войти"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#0055ff;\">Введите логин:</span></p></body></html>"))
        self.waring.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#2b2b2b;\"span></p></body></html>"))
