# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 350)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(10, 90, 421, 251))
        self.table.setStyleSheet("gridline-color: rgb(173, 173, 173);\n"
"font: 10pt \"Book Antiqua\";\n"
"background-color: rgb(239, 239, 239);\n"
"color: rgb(0, 85, 255);")
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.text_search = QtWidgets.QTextEdit(Form)
        self.text_search.setGeometry(QtCore.QRect(10, 50, 421, 31))
        self.text_search.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.text_search.setObjectName("text_search")
        self.label_entername = QtWidgets.QLabel(Form)
        self.label_entername.setGeometry(QtCore.QRect(11, 10, 301, 31))
        self.label_entername.setStyleSheet("font: 16pt \"Book Antiqua\";")
        self.label_entername.setObjectName("label_entername")
        self.textEdit_weight = QtWidgets.QTextEdit(Form)
        self.textEdit_weight.setGeometry(QtCore.QRect(630, 50, 61, 31))
        self.textEdit_weight.setStyleSheet("font: 10pt \"Book Antiqua\";")
        self.textEdit_weight.setObjectName("textEdit_weight")
        self.label_qualityw = QtWidgets.QLabel(Form)
        self.label_qualityw.setGeometry(QtCore.QRect(440, 50, 201, 31))
        self.label_qualityw.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"Book Antiqua\";\n"
"")
        self.label_qualityw.setObjectName("label_qualityw")
        self.label_info = QtWidgets.QLabel(Form)
        self.label_info.setGeometry(QtCore.QRect(450, 100, 241, 71))
        self.label_info.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"Book Antiqua\";")
        self.label_info.setObjectName("label_info")
        self.button_add = QtWidgets.QPushButton(Form)
        self.button_add.setGeometry(QtCore.QRect(450, 290, 75, 23))
        self.button_add.setFocusPolicy(QtCore.Qt.TabFocus)
        self.button_add.setStyleSheet("font: 9pt \"Book Antiqua\";\n"
"background-color: rgb(218, 218, 218);")
        self.button_add.setObjectName("button_add")
        self.button_cancel = QtWidgets.QPushButton(Form)
        self.button_cancel.setGeometry(QtCore.QRect(530, 290, 75, 23))
        self.button_cancel.setStyleSheet("font: 9pt \"Book Antiqua\";\n"
"background-color: rgb(218, 218, 218);")
        self.button_cancel.setObjectName("button_cancel")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(610, 290, 75, 23))
        self.pushButton.setStyleSheet("font: 9pt \"Book Antiqua\";\n"
"background-color: rgb(218, 218, 218);")
        self.pushButton.setObjectName("pushButton_calc")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text_search.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Book Antiqua\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_entername.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#a33600;\">Введите название продукта:</span></p></body></html>"))
        self.label_qualityw.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#ac3900;\">Количество в граммах:</span></p></body></html>"))
        self.label_info.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.button_add.setText(_translate("Form", "Добавить"))
        self.button_cancel.setText(_translate("Form", "Отменить"))
        self.pushButton.setText(_translate("Form", "Ок"))
