# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 350)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(10, 90, 421, 251))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.text_search = QtWidgets.QTextEdit(Form)
        self.text_search.setGeometry(QtCore.QRect(10, 50, 421, 31))
        self.text_search.setObjectName("text_search")
        self.label_entername = QtWidgets.QLabel(Form)
        self.label_entername.setGeometry(QtCore.QRect(20, 10, 251, 31))
        self.label_entername.setObjectName("label_entername")
        self.textEdit_weight = QtWidgets.QTextEdit(Form)
        self.textEdit_weight.setGeometry(QtCore.QRect(613, 50, 61, 31))
        self.textEdit_weight.setObjectName("textEdit_weight")
        self.label_qualityw = QtWidgets.QLabel(Form)
        self.label_qualityw.setGeometry(QtCore.QRect(450, 55, 161, 21))
        self.label_qualityw.setObjectName("label_qualityw")
        self.label_info = QtWidgets.QLabel(Form)
        self.label_info.setGeometry(QtCore.QRect(450, 100, 191, 91))
        self.label_info.setObjectName("label_info")
        self.button_add = QtWidgets.QPushButton(Form)
        self.button_add.setGeometry(QtCore.QRect(500, 290, 75, 23))
        self.button_add.setFocusPolicy(QtCore.Qt.TabFocus)
        self.button_add.setObjectName("button_add")
        self.button_cancel = QtWidgets.QPushButton(Form)
        self.button_cancel.setGeometry(QtCore.QRect(580, 290, 75, 23))
        self.button_cancel.setObjectName("button_cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_entername.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите название продукта:</span></p></body></html>"))
        self.label_qualityw.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Количесвто в граммах:</span></p></body></html>"))
        self.label_info.setText(_translate("Form", " "))
        self.button_add.setText(_translate("Form", "Добавить"))
        self.button_cancel.setText(_translate("Form", "Отменить"))
