# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(198, 160)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 20, 61, 21))
        self.label.setStyleSheet("font: 75 8pt \"Book Antiqua\";\n"
"color: rgb(63, 63, 63);")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 60, 136, 86))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_calc = QtWidgets.QPushButton(self.widget)
        self.pushButton_calc.setStyleSheet("font: 9pt \"Book Antiqua\";\n"
"background-color: rgb(218, 218, 218);")
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.verticalLayout.addWidget(self.pushButton_calc)
        self.pushButton_add_prod = QtWidgets.QPushButton(self.widget)
        self.pushButton_add_prod.setStyleSheet("font: 9pt \"Book Antiqua\";\n"
"background-color: rgb(218, 218, 218);")
        self.pushButton_add_prod.setObjectName("pushButton_add_prod")
        self.verticalLayout.addWidget(self.pushButton_add_prod)
        self.pushButton_ex = QtWidgets.QPushButton(self.widget)
        self.pushButton_ex.setStyleSheet("font: 9pt \"Book Antiqua\";\n"
"background-color: rgb(218, 218, 218);")
        self.pushButton_ex.setObjectName("pushButton_ex")
        self.verticalLayout.addWidget(self.pushButton_ex)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Меню</span></p></body></html>"))
        self.pushButton_calc.setText(_translate("Form", "Пересчитать калории"))
        self.pushButton_add_prod.setText(_translate("Form", "Добавить продукт"))
        self.pushButton_ex.setText(_translate("Form", "Выйти"))
